site_name: Kubernetes Home Lab
site_description: Bare-metal Kubernetes home lab documentation
site_author: Arnaud Kaninda
docs_dir: src
site_dir: site
repo_url: https://github.com/kaninda/kubernetes-home-lab
repo_name: kaninda/kubernetes-home-lab

theme:
  name: material
  language: en

  features:
    - navigation.tabs              # ðŸ”¥ menu horizontal
    - navigation.tabs.sticky       # onglets toujours visibles
    - navigation.sections          # groupes dans la sidebar
    - navigation.expand            # tout ouvert par dÃ©faut
    - navigation.instant
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy            # bouton copier sur le code
    - content.action.edit
    - content.action.view

  palette:
    # Auto (systÃ¨me)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch theme

    # Light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Home: index.md

  - Overview:
      - Introduction: overview.md
      - Hardware: hardware.md
      - Network Topology: network-topology.md
      - Logical Architecture: logical-architecture.md

  - Core Installation:
      - OS Preparation: os-preparation.md
      - Kubernetes Installation (kubeadm): kubernetes-install.md
      - CNI (Calico): cni-calico.md
      - Join Workers: worker-join.md

  - Networking & Exposure:
      - Gateway API: gateway-api.md
      - NGINX Gateway Fabric: nginx-gateway.md
      - Cloudflare Tunnel: cloudflare-tunnel.md
      - DNS & Domain Setup: dns-setup.md

  - GitOps:
      - ArgoCD Installation: argocd-install.md
      - ArgoCD Exposure via Gateway: argocd-exposure.md
      - GitOps Workflow: gitops-workflow.md

  - Operations:
      - Validation: validation.md
      - Kubernetes Reset: kubernetes-reset.md
